In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
data=pd.read_csv(r"C:\Users\DELL\Downloads\ML Linear Regression Home Price Prediction & Analysis Project  Resource16932049360.csv")

In [9]:
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [12]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [16]:
data.isnull().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [18]:
data[data["Distance"].isnull()].index
data.drop(data[data["Distance"].isnull()].index,inplace=True)

In [20]:
data[data["CouncilArea"].isnull()].index
data.drop(data[data["CouncilArea"].isnull()].index,inplace=True)
data[data["Regionname"].isnull()].index
data.drop(data[data["Regionname"].isnull()].index,inplace=True)
data[data["Propertycount"].isnull()].index
data.drop(data[data["Propertycount"].isnull()].index,inplace=True)

In [22]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [24]:
data=data.drop(["Address","Postcode","YearBuilt","Lattitude","Longtitude","Date"],axis=1)

In [26]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

In [28]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             0
Bedroom2          8214
Bathroom          8223
Car               8725
Landsize         11807
BuildingArea     21112
CouncilArea          0
Regionname           0
Propertycount        0
dtype: int64

In [30]:
data["Landsize"]=data["Landsize"].fillna(data["Landsize"].mean())
data["BuildingArea"]=data["BuildingArea"].fillna(data["BuildingArea"].mean())
data["Price"]=data["Price"].fillna(data["Price"].mean())

In [32]:
data[["Bedroom2","Bathroom","Car"]]=data[["Bedroom2","Bathroom","Car"]].fillna(0)

In [34]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,1.050210e+06,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1.480000e+06,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1.035000e+06,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,1.050210e+06,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1.465000e+06,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1.480000e+06,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,8.880000e+05,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,7.050000e+05,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1.140000e+06,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1.020000e+06,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

In [36]:
data["Method"].unique()

array(['SS', 'S', 'VB', 'SP', 'PI', 'SN', 'W', 'PN', 'SA'], dtype=object)

In [38]:
data["SellerG"].unique()

array(['Jellis', 'Biggin', 'Rounds', 'Nelson', 'Collins', 'Dingle',
       'Purplebricks', 'Greg', 'Philip', 'LITTLE', 'Kay', 'Beller',
       'Marshall', 'hockingstuart', 'Brad', 'Maddison', 'Barry',
       'Airport', 'Considine', 'Rendina', 'Ray', 'Propertyau', 'McDonald',
       'Frank', 'Prof.', 'Harcourts', 'Thomson', 'Buxton', 'RT',
       "Sotheby's", 'Cayzer', 'Chisholm', 'McGrath', 'Brace', 'Miles',
       'Holland', 'Love', 'Thomas', 'Barlow', 'Sweeney', 'Village', 'Jas',
       'Williams', 'Gunn&Co', 'Burnham', 'Point', 'Compton', 'FN',
       'Hunter', 'Raine&Horne', 'Noel', 'Hodges', 'Gary', 'Fletchers',
       'Woodards', 'Raine', 'Alexkarbon', 'Walshe', 'Weda', 'Stockdale',
       'Tim', 'Buxton/Marshall', 'AIME', 'Moonee', 'HAR', 'Edward', 'RW',
       'North', 'MICM', 'Ascend', 'Christopher', 'Morrison', 'Bekdon',
       'Mandy', 'R&H', 'Fletchers/One', 'Lindellas', 'Appleby', 'Assisi',
       'One', 'Owen', 'Parkes', 'C21', 'Century', "O'Brien", 'Bayside',
       'Anderson', 'Paul', 'hockingstuart/Buxton', 'Smart', 'First',
       'Matthew', 'Melbourne', 'Nick', 'Allens', 'Bells', 'Nguyen',
       'Trimson', 'Douglas', 'Batty', 'GL', 'YPA', "Tiernan's", 'J',
       'Castran', 'Branon', 'Rodney', 'Joseph', 'Harrington', 'Galldon',
       'Grantham', 'Chambers', 'Pagan', 'Peter',
       'hockingstuart/Advantage', 'Ross', 'Rayner', 'Garvey',
       "O'Donoghues", 'Hamilton', 'Weast', 'Kelly', 'Property',
       "Private/Tiernan's", 'Australian', 'Bustin', "Abercromby's",
       'Whiting', 'iTRAK', 'Del', 'Caine', 'Nicholson', 'JMRE', 'ASL',
       'Changing', 'Re', 'RE', 'Walsh', 'Foxtons', 'Ham', 'Darren', 'Vic',
       'Haughton', 'Scott', 'Pride', 'Morleys', 'Wilson',
       'Buxton/Advantage', 'Professionals', 'Joe', 'Red',
       'hockingstuart/Jellis', 'Craig', 'Naison', 'Sweeney/Advantage',
       'Reach', 'Domain', 'Eview', 'Jason', "D'Aprano", 'Charlton',
       'CASTRAN', 'Wood', 'William', 'Coventry', 'Buckingham', 'Nardella',
       'Karen', 'LJ', 'Shape', 'Direct', 'Fletchers/Fletchers', 'Besser',
       'Johnston', 'Avion', 'Redina', 'Clairmont', 'Lucas', 'Dixon',
       'Xynergy', 'Elite', 'Buxton/Find', 'W.B.', 'Leased',
       'Harcourts/Barry', 'Win', 'Collings', 'New', 'Parkinson', 'Geoff',
       'hockingstuart/Barry', 'Blue', 'MSM', 'Steveway',
       'hockingstuart/Village', 'VICPROP', 'Inner', 'Meadows', 'Allan',
       'S&L', 'Crane', 'Calder', 'Metro', 'Homes', 'Zahn', 'Mason',
       'Landfield', 'David', 'Luxe', 'Prowse', 'Ken', 'Rombotis', 'iOne',
       'hockingstuart/Sweeney', 'Iconek', 'Luxton', 'Hooper', 'JRW',
       'Oak', 'White', 'Jim', 'Weston', '@Realty', 'Reed', 'Oriental',
       'Max', 'Steller', 'Rosin', 'Real', 'Jeffrey', 'Hall', 'Icon',
       'buyMyplace', 'WHITEFOX', 'Christou', 'Marvelli', "Grant's",
       'Hoskins', 'Gardiner', 'McLennan', 'Triwest', 'Reliance',
       'PRDNationwide', 'Only', 'Leyton', 'iSell', 'Obrien', 'Maitland',
       'Millership', 'L', 'Emerson', 'Follett', 'Ash', 'LLC', 'Ace',
       'Flannagan', 'Carter', 'WeSell', 'M.J', 'iProperty',
       'Hayeswinckle', 'Schroeder', 'iHomes', 'VICProp', 'REMAX', 'Space',
       'Victory', 'Aumeca', 'Mindacom', 'Ryder', 'Sanctuary', 'Leeburn',
       'Asset', 'Westside', 'Sell', 'Mitchell', 'Darras', 'U', 'Nicholas',
       'Rexhepi', 'Keatings', 'Aquire', 'Conquest', 'Prime', 'Donovan',
       'Community', 'Free', 'Veitch', 'John', 'Peake', 'Ristic', 'JY',
       'Upper', 'Daniel', 'VicHomes', 'TRUE', 'McNaughton', 'Leading',
       'Bullen', 'Better', 'Boutique', 'Royston', 'Langwell', 'Silver',
       'Wyndham', 'Kaye', 'Nicholls', 'Bowman', 'Just', 'Home', 'Le',
       'Cooper', 'Black', 'The', 'Open', 'Roger', 'McEwing', 'Sandhurst',
       'Boran', 'hockingstuart/hockingstuart', 'Area', 'MJ', 'Eric', 'SN',
       'Waterfront', 'P', 'PRD', 'Bombay', 'Quinta', 'T', 'Tanner', 'LJH',
       'Munn', 'Knight', 'Justin', 'Blackbird', 'Sweeney/Burnham', 'H',
       'Alex', 'Can', 'Pavilion', 'Benchmark', 'Gellibrand',
       'hockingstuart/Harcourts', 'Charter', 'Surreal', 'Vicprop', 'A',
       'Upside', 'OBrien', 'Meallin', 'Malvern', 'Mark', 'Bradly', 'For',
       'Peninsula', 'Sutherland', 'Leaders', 'Spencer',
       'McGrath/Langwell', 'Benlor', 'Burns', 'Sterling', 'K.R.Peters',
       'Buxton/Buxton', 'CarlinSmith', 'Gold', 'Hill', 'People',
       'hockingstuart/Biggin', 'Mega', 'Skad', 'Ruralco', 'Create',
       'Janice', 'R', 'G&H', 'Commercial', 'PSP', 'hockingstuart/Cayzer',
       'Unity', 'Sprint', 'McGrath/Buxton', 'hockingstuart/Marshall',
       'McGrath/First', 'voglwalpole', 'Watermark', 'Methven'],
      dtype=object)

In [40]:
data["Landsize"].unique()

array([ 126.,  202.,  156., ..., 1098., 1109., 1163.])

In [42]:
data["CouncilArea"].unique()

array(['Yarra City Council', 'Moonee Valley City Council',
       'Port Phillip City Council', 'Darebin City Council',
       'Hobsons Bay City Council', 'Stonnington City Council',
       'Boroondara City Council', 'Monash City Council',
       'Glen Eira City Council', 'Whitehorse City Council',
       'Maribyrnong City Council', 'Bayside City Council',
       'Moreland City Council', 'Manningham City Council',
       'Melbourne City Council', 'Banyule City Council',
       'Brimbank City Council', 'Kingston City Council',
       'Hume City Council', 'Knox City Council', 'Maroondah City Council',
       'Casey City Council', 'Melton City Council',
       'Greater Dandenong City Council', 'Nillumbik Shire Council',
       'Cardinia Shire Council', 'Whittlesea City Council',
       'Frankston City Council', 'Macedon Ranges Shire Council',
       'Yarra Ranges Shire Council', 'Wyndham City Council',
       'Moorabool Shire Council', 'Mitchell Shire Council'], dtype=object)

In [44]:
data=pd.get_dummies(data,drop_first=True)

In [45]:
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,1.050210e+06,2.5,2.0,1.0,1.0,126.000000,160.2564,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
1,2,1.480000e+06,2.5,2.0,1.0,1.0,202.000000,160.2564,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
2,2,1.035000e+06,2.5,2.0,1.0,0.0,156.000000,79.0000,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
3,3,1.050210e+06,2.5,3.0,2.0,1.0,0.000000,160.2564,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
4,3,1.465000e+06,2.5,3.0,2.0,0.0,134.000000,150.0000,4019.0,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1.480000e+06,6.3,4.0,1.0,3.0,593.000000,160.2564,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34853,2,8.880000e+05,6.3,2.0,2.0,1.0,98.000000,104.0000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34854,2,7.050000e+05,6.3,2.0,1.0,2.0,220.000000,120.0000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34855,3,1.140000e+06,6.3,0.0,0.0,0.0,593.598993,160.2564,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34856,2,1.020000e+06,6.3,2.0,1.0,0.0,250.000000,103.0000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False

In [48]:
x=data.drop("Price",axis=1)
y=data["Price"]

In [50]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [51]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,train_size=0.8)

In [52]:
model=LinearRegression()

In [53]:
model.fit(x_train,y_train)

LinearRegression()

In [54]:
model.score(x_train,y_train)

0.49133588959555063

In [58]:
model.score(x_test,y_test)

0.48429240023199405

In [59]:
lis=[SVR,DecisionTreeRegressor,RandomForestRegressor,KNeighborsRegressor]

In [60]:
for i in lis:
    model=i()
    model.fit(x_train,y_train)
    print(i)
    print(model.score(x_train,y_train))
    print(model.score(x_test,y_test))

<class 'sklearn.svm._classes.SVR'>
0.00012320351493833037
0.00011107663776788179
<class 'sklearn.tree._classes.DecisionTreeRegressor'>
0.9814419309382786
0.173172904016327
<class 'sklearn.ensemble._forest.RandomForestRegressor'>
0.9212301211899514
0.5567439175802946
<class 'sklearn.neighbors._regression.KNeighborsRegressor'>
0.5464297054834795
0.34420064065638833

In [61]:
from sklearn.model_selection import KFold,cross_val_score

In [65]:
for i in lis:
    kf=KFold(n_splits=5)
    print(i)
    print(cross_val_score(i(),x,y,cv=kf))

<class 'sklearn.svm._classes.SVR'>
[-0.03524778 -0.00705854 -0.00281885 -0.00016995 -0.00161386]
<class 'sklearn.tree._classes.DecisionTreeRegressor'>
[-0.14288136  0.15750759  0.21281949  0.26847993  0.23246611]
<class 'sklearn.ensemble._forest.RandomForestRegressor'>
[0.47992846 0.506845   0.54172144 0.53239746 0.53063618]
<class 'sklearn.neighbors._regression.KNeighborsRegressor'>
[0.2374568  0.24828631 0.2367468  0.35772455 0.28612672]

In [ ]:
model = 
model.fit(x_train,y_train)
model.score(x_train,y_train)
model.score(x_test,y_test)